# Basic Python

## 1. Split this string

In [8]:
s = "Hi there Rasmia!"

In [9]:
print(s.split())

['Hi', 'there', 'Rasmia!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {planet} is {distance} kilometeres".format(planet="Earth",distance=12742))

The diameter of Earth is 12742 kilometeres


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [18]:
array=np.arange(20,35,2)
print (array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z=np.concatenate((x,y),axis=0)
print(z)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [22]:
import pandas as pd


In [23]:
data=[["Rasmia",20],["Rabiya",16],["Ziad",18],["Aadil",12]]
data1=pd.DataFrame(data,columns=["name","age"])
print(data1)

     name  age
0  Rasmia   20
1  Rabiya   16
2    Ziad   18
3   Aadil   12


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [24]:
data=pd.date_range(start="1-01-2023",end="10-02-2023",freq="5h")
print(data)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 05:00:00',
               '2023-01-01 10:00:00', '2023-01-01 15:00:00',
               '2023-01-01 20:00:00', '2023-01-02 01:00:00',
               '2023-01-02 06:00:00', '2023-01-02 11:00:00',
               '2023-01-02 16:00:00', '2023-01-02 21:00:00',
               ...
               '2023-09-30 02:00:00', '2023-09-30 07:00:00',
               '2023-09-30 12:00:00', '2023-09-30 17:00:00',
               '2023-09-30 22:00:00', '2023-10-01 03:00:00',
               '2023-10-01 08:00:00', '2023-10-01 13:00:00',
               '2023-10-01 18:00:00', '2023-10-01 23:00:00'],
              dtype='datetime64[ns]', length=1316, freq='5H')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [26]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [27]:
data=pd.DataFrame(lists,columns=["s.no","words","marks"])
print(data)

   s.no words  marks
0     1   aaa     22
1     2   bbb     25
2     3   ccc     24
